utils::globalVariables(c(
  "justica",
  "numero",
  "id",
  "tribunal",
  "value",
  "indice",
  "name",
  "input_date",
  "user",

  ".", ":=", "ano_distribuicao", "assunto", "classe_processual",
  "cod_filhos", "cod_pai",
  "code_muni", "codigo", "codigoNacional", "codigoPaiNacional",
  "codigo_municipio_ibge", "codigo_orgao", "data", "dataHora",
  "data_ajuizamento",
  "descricao", "descricao.x", "descricao.y", "descricao_filha",
  "dig_calculado",
  "dsc_sistema", "dscr", "file_json", "ibge", "id_sub", "id_tribunal",
  "identificadorMovimento", "inc_assunto_generico",
  "inc_assunto_nao_bate_com_tpu", "inc_assunto_vazio", "inc_classe",
  "inc_classe_assunto_raro", "inc_cod_pai_faltante", "inc_data", "inc_digito",
  "inc_eletronico", "inc_id_mov_segue_ordem_cronologica", "inc_justica",
  "inc_mov_demorada", "inc_mov_relevante_ordenada",
  "inc_nao_e_assunto_principal", "inc_orgao", "inc_processo_longo",
  "inc_responsavel_mov", "inc_sistema", "inc_valor", "indice_normalizado",
  "info_assunto", "info_mov_faltante", "jj", "justica_nproc", "mapa",
  "media",
  "mov_ordem", "movimento", "n", "n_sistema", "num_sub", "orgaoJulgador",
  "principal", "proc_el", "processo_longo", "ranking", "rowid", "sigla",
  "sistema_provavel", "sol_digito", "sol_eletronico",
  "sol_id_mov_segue_ordem_cronologica", "sol_mov_relevante_ordenada",
  "sol_responsavel_mov", "tipoResponsavelMovimento", "tipo_codigo",
  "tribunal_nproc", "valor_causa", "where"
))
